### PR TITLE
Fix issue #71: [RULE] Enforce Usage of `HttpsError` Instead of `throw…

### LINKED ISSUE #71: [RULE] Enforce Usage of `HttpsError` Instead of `throw new Error` in `functions/src`
Here's the expanded ESLint rule request using the provided GitHub Issue template:

### **High-Level Overview**  
This ESLint rule aims to enforce a consistent error-handling pattern in the `functions/src` directory by warning against using `throw new Error`. Instead, developers should use the custom `HttpsError` class from `functions/src/util/errors/HttpsError.ts`. 

The `HttpsError` class provides structured error handling, aligning with gRPC and HTTP error code conventions, ensuring errors are categorized and propagated in a standardized way. Using generic `Error` instances (`throw new Error`) can lead to inconsistencies, reduced readability, and difficulty debugging or integrating with services relying on well-defined error types.  

This rule is important for BluMint’s codebase to ensure a uniform error-handling strategy that aligns with our engineering standards and improves maintainability across cloud functions.

---

### **Example Code (Bad vs. Good)**  

**Bad Code:**  
```javascript
function fetchUserData(userId) {
  if (!userId) {
    throw new Error('User ID is required');
  }
  // Fetch user data logic...
}
```

**Good Code:**  
```javascript
import { HttpsError } from '@/functions/src/util/errors/HttpsError';

function fetchUserData(userId) {
  if (!userId) {
    throw new HttpsError('INVALID_ARGUMENT', 'User ID is required', `User ID provided ${userId}`);
  }
  // Fetch user data logic...
}
```

---

### **Additional Notes**  
- **Scope:**  
  The rule should only apply to files in the `functions/src` directory. Files outside this directory should not be affected, as error-handling conventions might differ.  

- **Autofix:**  
  This rule should not try to autofix. Only throw an error.

- **Existing Alternatives:**  
  Related ESLint rules (e.g., `no-throw-literal`) enforce throwing only `Error` objects but don't address the use of custom error classes like `HttpsError`.

---

#### **1. Use of Legacy Errors in Tests or Migrations**  
- **Issue:** Legacy code or tests might intentionally use `throw new Error`.  
- **Solution:** Allow exceptions via inline comments (`// eslint-disable-next-line`) and configuration to ignore specific files/directories (e.g., `tests/`).

---

#### **2. Dynamic or Custom Error Classes**  
- **Issue:** Some code may use custom error classes other than `HttpsError`.  
  Example:  
  ```javascript
  class CustomError extends Error {
    constructor(message) {
      super(message);
    }
  }
  throw new CustomError('Custom error message');
  ```  
- **Solution:** The rule should flag only `throw new Error`, not other error classes.  

---

### PR DESCRIPTION
**Pull request by oconnorjoseph**
Fixes #71 
… new Error` in `functions/src`

## Summary by CodeRabbit

- **New Features**
	- Introduced a new rule, `require-https-error`, to enforce the use of `HttpsError` in specific directories.

- **Bug Fixes**
	- Added error reporting for violations of the `require-https-error` rule.

- **Tests**
	- Implemented tests for the `require-https-error` rule to validate correct error handling scenarios.

### CODE REVIEW

File: src/rules/require-https-error.ts [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+    },
+  },
+  defaultOptions: [],
+  create(context) {
+    const filename = context.getFilename();
+
+    // Only apply rule to files in functions/src directory
+    if (!filename.includes('functions/src')) {
+      return {};
+    }
```
Comment (oconnorjoseph) [inline src/rules/require-https-error.ts:26]: We can enforce this on the frontend as well.

File: src/rules/require-https-error.ts
Comment (oconnorjoseph) [inline src/rules/require-https-error.ts:1]: We should also update this rule to forbid the use the firebase-admin's `HttpsError` over our proprietary `HttpsError`.
